### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Ticoy04**
Character Sketch -  Noel Barlowe - SC’S STEP FATHER(Male)

### CODE REVIEW

**Review by jtinosa — CHANGES_REQUESTED** [review]
Export mo yung image Regie

**Comment by Ticoy04** [comment]
Sir @jtinosa ayan na po.
Gamedev progress(1)

**Review by jtinosa — CHANGES_REQUESTED** [review]
Export mo yung image to png, wag yung screenshot nung image.

**Comment by Ticoy04** [comment]
na commit ko na po ulit sir, need ko po ba ulit ipull?

**Review by jtinosa — APPROVED** [review]

**Pull request merged**
